config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  root to: "contacts#index"
  
  resources :contacts, only: %i[index show destroy]
  resources :imports do
    scope module: :imports do
      resource :pair_columns, only: %i[show edit]
      resource :schedules, only: :create
      resource :clear_logs, only: :destroy
    end
  end
end

app/models/import.rb
class Import < ApplicationRecord
  include AASM
  
  UPLOADABLE_ATTRIBUTES = %w[address birthdate credit_card_number email name phone].freeze

  has_one_attached :file
  belongs_to :user
  has_many :contacts
  has_many :column_pairings, dependent: :destroy
  accepts_nested_attributes_for :column_pairings, allow_destroy: true

  after_create :initialize_column_pairings
  
  paginates_per 50
  
  aasm column: :current_status do
    state :on_hold, initial: true
    state :processing
    state :failed
    state :finished

    event :restart, after_commit: :notify_status_change do
      transitions to: :on_hold
    end
    
    event :start_process, after_commit: :notify_status_change do
      transitions to: :processing
    end
    
    event :fail, after_commit: :notify_status_change do
      transitions from: :processing, to: :failed
    end
    
    event :finish, after_commit: :notify_status_change do
      transitions from: :processing, to: :finished
    end
  end

  def notify_status_change
    broadcast_update_later_to self, target: "import_#{id}_status", partial: 'imports/status'
  end

  def notify_logs_change
    broadcast_update_later_to self, target: "import_#{id}_logs", partial: 'imports/logs'
  end

  def clear_logs
    self.log['logs'] = []
  end

  private

  def initialize_column_pairings
    return if self.column_pairings.any?

    self.column_pairings = UPLOADABLE_ATTRIBUTES.map { |attr| self.column_pairings.find_or_create_by(local_column: attr) }
  end
end

# == Schema Information
#
# Table name: imports
#
#  id             :bigint           not null, primary key
#  current_status :string
#  log            :jsonb
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  user_id        :integer
#
# Indexes
#
#  index_imports_on_current_status  (current_status)
#  index_imports_on_user_id         (user_id)
#

app/controllers/imports/clear_logs_controller.rb
class Imports::ClearLogsController < ApplicationController
  before_action :find_import

  def destroy
    @import.clear_logs
    @import.save!

    respond_to do |format|
      format.turbo_stream
      format.html do
        flash[:success] = "Logs cleared!"
        redirect_to import_path(@import)
      end
    end
  rescue StandardError => e
    flash[:error] = "Error: #{e.message}"
    redirect_to import_path(@import)
  end

  private

  def find_import
    @import = current_user.imports.find_by(id: params[:import_id])
  end
end

app/controllers/imports/pair_columns_controller.rb
class Imports::PairColumnsController < ApplicationController
  before_action :find_import

  def show
    load_column_pairings
    load_csv_headers
  end

  def edit
    load_column_pairings
    load_csv_headers

    render layout: params[:layout].present?
  end

  private

  def update_params
    params.require(:import).permit({
      column_pairings: %i[csv_column local_column _destroy]
    })
  end

  def find_import
    @import = current_user.imports.includes(:column_pairings).find_by(id: params[:import_id])
  end

  def load_column_pairings
    @column_pairings = @import.column_pairings.order(local_column: :asc)
  end

  def load_csv_headers
    csv_file_headers = CsvHeadersForFileService.new(@import.file).call
    current_csv_columns = @column_pairings.pluck(:csv_column)

    @csv_headers = current_csv_columns.compact + csv_file_headers.reject { |h| current_csv_columns.include?(h) }
  end
end

app/controllers/imports/schedules_controller.rb
class Imports::SchedulesController < ApplicationController
  before_action :find_import

  def create
    @import.restart!
    ImportContactsJob.perform_later(@import.id, current_user.id)

    respond_to do |format|
      format.html do
        flash[:success] = "Import scheduled to process!"
        redirect_to import_path(@import)
      end
    end
  rescue StandardError => e
    flash[:error] = "Error: #{e.message}"
    redirect_to import_path(@import)
  end

  private

  def find_import
    @import = current_user.imports.find_by(id: params[:import_id])
  end
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_import!, only: %i[show update destroy]

  def index
    @imports = user_imports
  end

  def new
    @import = current_user.imports.new
  end
  
  def create
    @import = current_user.imports.new(create_params)
    @import.save!

    flash[:success] = "Import created successfully!"
    redirect_to import_pair_columns_path(@import)
  rescue StandardError => e
    flash[:error] = "Error: #{e.message}"
    redirect_to action: :new
  end
  
  def show
    load_column_pairings
    load_csv_headers
  end
  
  def update
    @import.update!(update_params)

    respond_to do |format|
      format.turbo_stream do
        load_column_pairings
        load_csv_headers
        @autoupdate_form = params[:autoupdate_form] == 'true' ? true : false
        flash.now[:success] = 'Columns paired successfully!'
      end
      format.html do
        if params[:schedule_job].present?
          @import.restart!
          ImportContactsJob.perform_later(@import.id, current_user.id)
          flash[:success] = "Contacts are now being imported!"
        else
          flash[:success] = "Columns paired successfully!"
        end
        redirect_to import_path(@import)
      end
    end

  rescue StandardError => e
    flash[:error] = "Error: #{e.message}"
    redirect_to @import
  end
  
  def destroy
    @import.destroy!

    flash[:success] = "Import deleted successfully"
    redirect_to action: :index
  rescue StandardError => e
    flash[:error] = "Error: #{e.message}"
    redirect_to @import
  end
  
  private
  
  def create_params
    params.require(:import).permit(%i[file])
  end
  
  def update_params
    params.require(:import).permit(:created_at, {
      column_pairings_attributes: %i[csv_column local_column position _destroy id]
    })
  end
  
  def find_import!
    @import = current_user.imports.includes(:column_pairings).find_by!(id: params[:id])
  rescue StandardError => e
    flash[:error] = "Import not found"
    redirect_to action: :index
  end

  def user_imports
    current_user.imports.order(created_at: :desc).page(params[:page]).per(params[:per_page])
  end

  def load_column_pairings
    @column_pairings = @import.column_pairings.order(local_column: :asc)
  end

  def load_csv_headers
    csv_file_headers = CsvHeadersForFileService.new(@import.file).call
    current_csv_columns = @column_pairings.pluck(:csv_column)

    @csv_headers = current_csv_columns.compact + csv_file_headers.reject { |h| current_csv_columns.include?(h) }
  end
end

app/helpers/imports/clear_logs_helper.rb
module Imports::ClearLogsHelper
end

app/helpers/imports/pair_columns_helper.rb
module Imports::PairColumnsHelper
end

app/helpers/imports/schedules_helper.rb
module Imports::SchedulesHelper
end

app/helpers/imports_helper.rb
module ImportsHelper
  def import_badge_color(import)
    return 'bg-success' if import.finished?
    return 'bg-danger' if import.failed?
    return 'bg-warning' if import.processing?
    return 'bg-primary'
  end
end

app/views/imports/_columns.html.erb
<ul class="clean-list">
  <li class="border-bottom">
    <div class="headers row mt-4">
      <span class="col-6 fw-bold">
        Attribute
      </span>
      <span class="col-6 fw-bold">
        CSV Column
      </span>
    </div>
  </li>
  <li>
    <div class="row">
      <div class="col-6">
        <ul class="clean-list striped-rows">
          <% column_pairings.each_with_index do |column_pair, index| %>
            <li class="text-muted">
              <%= column_pair.local_column %>
              <%= form.fields_for :column_pairings, column_pair do |ff| %>
                <%= ff.hidden_field :csv_column, value: column_pair.csv_column.presence || headers[index], data: {value: true}, onchange: defined?(onChange) && onChange %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="col-6">
        <ul
          class="clean-list striped-rows"
          <% if defined?(sortable) %>
            data-controller="attributes-dragging"
            data-attributes-dragging-animation-value="150"
            data-attributes-dragging-resource-name-value="column_pairing"
            data-attributes-dragging-handle-value=".handle"
            data-attributes-dragging-autoupdate-value="<%= (defined?(onChange) && onChange) || false %>"
          <% end %>
        >
          <% headers.each_with_index do |header, index| %>
            <li
              <% if defined?(sortable) %>
                class="sortable-row"
              <% end %>
            >
              <div class="d-flex align-items-center">
                <% if defined?(sortable) %>
                  <span class="handle mx-2">
                    <i class="fas fa-grip-vertical"></i>
                  </span>
                <% end %>
                <span class="value"><%= header %></span>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </li>
</ul>

app/views/imports/_created_at.html.erb
<%= form.text_field :created_at, class: 'form-control', data: { controller: 'date-picker' } %>

app/views/imports/_form.html.erb
<%= form_with(model: import, id: "#{dom_id(import)}_form") do |f| %>
  <div class="row mt-3">
    <div class="col-12 d-flex align-items-center">
      <%= f.label(:file, class: 'form-label') { 'CSV File' } %>
    </div>
    <div class="col-4">
      <%= f.file_field :file, class: 'form-control' %>
    </div>
  </div>

  <div class="row my-4">
    <div class="col-md-12">
      <%= f.submit 'Import', class: 'btn btn-primary' %>
      <%= link_to 'Cancel', imports_path, class: 'btn btn-link' %>
    </div>
  </div>
<% end %>

app/views/imports/_import.html.erb
<tr>
  <td><%= link_to import.id, import_path(import) %></td>
  <td>
    <%= turbo_stream_from import %>
    <%= turbo_frame_tag "#{dom_id(import)}_status" do %>
      <%= render 'status', import: import %>
    <% end %>
  </td>
  <td><%= link_to import.created_at.strftime('%Y/%m/%d'), import_path(import) %></td>
  <td>
    <% if import.failed? %>
      <%= link_to(
        edit_import_pair_columns_path(import),
        class: 'btn btn-primary',
        data: {
          turbo_frame: 'pair_columns_modal_body',
          action: 'click->modal#show',
          controller: 'modal',
          modal_modal_id_value: '#importPairColumnsModal'
        }
      ) do %>
        <i class="fa-solid fa-code-compare"></i> Pair Columns
      <% end %>
      <%= link_to import_schedules_path(import), class: 'btn btn-warning mx-2', method: :post, remote: true do %>
        <i class="fa-solid fa-arrows-rotate"></i> Re-Import
      <% end %>
    <% end %>
  </td>
</tr>

app/views/imports/_log.html.erb
<tr class="<%= log['error'] ? 'table-danger' : '' %>">
  <td><%= log['index_in_file'] + 1 %></td>
  <td><%= log['description'] %></td>
  <td><%= log['contact_info'].to_h %></td>
</tr>

app/views/imports/_logs.html.erb
<div class="table">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Index</th>
        <th>Error description</th>
        <th>Contact Info</th>
      </tr>
    </thead>
    <tbody>
      <% if import.log['logs'].empty? %>
        <tr>
          <td colspan="7" class="text-muted text-center">No logs found</td>
        </tr>
      <% else %>
        <%= render partial: 'imports/log', collection: import.log['logs'] %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/imports/_pair_columns_modal.html.erb
<%= render 'shared/modal', id: "importPairColumnsModal", title: "Pair Columns" do %>
  <% content_for :body do %>
    <div id="spinner"></div>
    <%= turbo_frame_tag "modal_messages" do %>
      <%= render('imports/pair_columns/messages', import: @import, messages: flash) if @import.present? %>
    <% end %>
    <%= turbo_frame_tag 'pair_columns_modal_body' do %>
      <%= render('imports/pair_columns/form', import: @import, column_pairings: @column_pairings, headers: @csv_headers) if @import.present? %>
    <% end %>
  <% end %>
  <% content_for :footer do %>
    <button type="submit" class="btn btn-primary">Save changes</button>
  <% end %>
<% end %>

app/views/imports/_status.html.erb
<%= render(StatusBadgeComponent.new(color: import_badge_color(import)).with_content(t("statuses.#{import.current_status}"))) %>

app/views/imports/clear_logs.turbo_stream.erb
<%= turbo_stream.replace "#{dom_id(@import)}_logs" do %>
  <%= render "logs", import: @import %>
<% end %>

app/views/imports/index.html.erb
<h1>Imports</h1>
<div class="d-flex justify-content-end mt-3">
  <%= link_to new_import_path, class: 'btn btn-primary' do %>
    <i class="fa-solid fa-upload"></i> Upload file
  <% end %>
</div>
<div class="table-responsive mt-3">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Status</th>
        <th scope="col">Uploaded on</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% if @imports.empty? %>
        <tr>
          <td colspan="4" class="text-muted text-center">No imports found</td>
        </tr>
      <% else %>
        <%= render @imports %>
      <% end %>
    </tbody>
  </table>
  <%= render 'pair_columns_modal' %>
</div>
<% if @imports.total_count > 0 %>
  <div class="mb-2 row">
    <div class="col text-center text-muted">
      Total imports: <%= @imports.total_count %>
    </div>
  </div>
<% end %>
<%= paginate @imports %>

app/views/imports/new.html.erb
<h1>Import Contacts</h1>
<div class="mt-4">
  <%= render 'form', import: @import %>
</div>

app/views/imports/show.html.erb
<%= turbo_stream_from @import %>
<%= render partial: 'shared/breadcrumbs', locals: { items: [link_to('Imports', imports_path), @import.id] } %>
<h1>Import</h1>
<div class="d-flex justify-content-end mt-3">
  <%= link_to import_schedules_path(@import), class: 'btn btn-warning mx-2', method: :post do %>
    <i class="fa-solid fa-arrows-rotate"></i> Re-Import
  <% end %>
  <%= button_to @import, class: 'btn btn-danger', method: :delete, form: { data: { turbo: false, confirm: 'Are you sure?' } } do %>
    Delete
  <% end %>
</div>
<div class="row mt-3">
  <div class="col-12 col-md-4 d-flex align-items-center">
    <%= label_tag(:id, 'ID', class: 'form-label') %>
  </div>
  <div class="col-12 col-md-8">
    <%= text_field_tag :id, @import.id, class: 'form-control', readonly: true, disabled: true %>
  </div>
</div>
<div class="row mt-3">
  <div class="col-12 col-md-4 d-flex align-items-center">
    <%= label_tag(:current_status, 'Status', class: 'form-label') %>
  </div>
  <div class="col-12 col-md-8">
    <%= turbo_frame_tag "#{dom_id(@import)}_status" do %>
      <%= render 'status', import: @import %>
    <% end %>
  </div>
</div>
<div class="row mt-3">
  <div class="col-12 col-md-4 d-flex align-items-center">
    <%= label_tag(:file, 'Uploaded filename', class: 'form-label') %>
  </div>
  <div class="col-12 col-md-8">
    <%= text_field_tag :file, @import.file.filename, class: 'form-control', readonly: true, disabled: true %>
  </div>
</div>
<div class="row mt-3">
  <div class="col-12 col-md-4 d-flex align-items-center">
    <%= label_tag(:created_at, 'Created on', class: 'form-label') %>
  </div>
  <div class="col-12 col-md-8">
    <%= turbo_frame_tag "#{dom_id(@import)}_created_at" do %>
      <%= form_with model: @import, id: "#{dom_id(@import)}_created_at_form" do |f| %>
        <%= render 'created_at', import: @import, form: f %>
      <% end %>
    <% end %>
  </div>
</div>
<div class="row mt-3">
  <div class="col-12 col-md-4 d-flex align-items-center">
    <%= label_tag(:column_pairings, 'Columns pairing', class: 'form-label') %>
  </div>
  <div class="col-12 col-md-8">
    <%= turbo_frame_tag "#{dom_id(@import)}_columns" do %>
      <%= form_with model: @import, id: "#{dom_id(@import)}_columns_form" do |f| %>
        <%= hidden_field_tag :autoupdate_form, true %>
        <%=
          render 'columns', {
            import: @import,
            column_pairings: @column_pairings,
            headers: @csv_headers,
            onChange: 'this.form.requestSubmit()',
            form: f,
            sortable: true
          } %>
      <% end %>
    <% end %>
  </div>
</div>

<h2 class="mt-4">Logs</h2>
<div class="d-flex justify-content-end mt-3">
  <%= button_to import_clear_logs_path(@import), class: 'btn btn-outline-danger', method: :delete, data: { turbo_method: :delete } do %>
    Clear Logs
  <% end %>
</div>
<%= turbo_frame_tag "#{dom_id(@import)}_logs" do %>
  <%= render "logs", import: @import %>
<% end %>

app/views/imports/update.turbo_stream.erb
<%= turbo_stream.replace "#{dom_id(@import)}_columns" do %>
  <%= form_with model: @import, id: "#{dom_id(@import)}_columns_form" do |f| %>
    <%= hidden_field_tag :autoupdate_form, @autoupdate_form %>
    <%= render 'columns', {
      import: @import,
      column_pairings: @column_pairings,
      headers: @csv_headers,
      onChange: @autoupdate_form ? 'this.form.requestSubmit()' : nil,
      form: f,
      sortable: true
    } %>
  <% end %>
<% end %>

<%= turbo_stream.replace "#{dom_id(@import)}_created_at" do %>
  <%= form_with model: @import, id: "#{dom_id(@import)}_created_at_form" do |f| %>
    <%= render 'created_at', import: @import, form: f %>
  <% end %>
<% end %>

<%= turbo_stream.append "modal_messages" do %>
  <%= render 'imports/pair_columns/messages', import: @import, messages: flash %>
<% end %>