config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  root to: "contacts#index"
  
  resources :contacts, only: %i[index show destroy]
  resources :imports do
    scope module: :imports do
      resource :pair_columns, only: %i[show edit]
      resource :schedules, only: :create
      resource :clear_logs, only: :destroy
    end
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  PHONE_REGEXP = /\A\(\+\d{1,}\)\s\d{3}(\S|\s)\d{3}(\S|\s)\d{2}(\S|\s)\d{2}((\S|\s)\d{2})?\z/
  NAME_REGEXP = /\A([a-zA-Z0-9]+(\s|\-)*)*\z/
  BIRTHDATE_REGEXP = /\A\d{4}\/\d{2}\/\d{2}\z|\A\d{4}\-\d{2}\-\d{2}\z/

  belongs_to :user
  belongs_to :import
  
  encrypts :credit_card_number
  
  validates :credit_card_number, presence: true, length: { minimum: 12, maximum: 16 }
  validates :credit_card_network, presence: true
  validates :last_4, presence: true, length: { is: 4 }
  validates :birthdate, presence: true, format: { with: BIRTHDATE_REGEXP }
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: { scope: :user_id }
  validates :address, presence: true
  validates :phone, format: { with: PHONE_REGEXP }
  validates :name, presence: true, format: { with: NAME_REGEXP }
  
  paginates_per 50
end

# == Schema Information
#
# Table name: contacts
#
#  id                  :bigint           not null, primary key
#  address             :string
#  birthdate           :string
#  credit_card_network :string
#  credit_card_number  :string
#  email               :string
#  last_4              :string
#  name                :string
#  phone               :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  import_id           :integer
#  user_id             :integer
#
# Indexes
#
#  index_contacts_on_email_and_user_id  (email,user_id) UNIQUE
#  index_contacts_on_import_id          (import_id)
#  index_contacts_on_user_id            (user_id)
#

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_contact!, only: %i[show destroy]

  def index
    @contacts = user_contacts
  end
  
  def show; end
  
  def destroy
    @contact.destroy!

    respond_to do |format|
      format.turbo_stream do
        @contacts = user_contacts
      end
      format.html do
        flash[:success] = 'Contact deleted'
        redirect_to action: :index
      end
    end
  rescue StandardError => e
    flash[:error] = "Error: #{e.message}"
    redirect_to @contact
  end
  
  private
  
  def find_contact!
    @contact = current_user.contacts.find_by!(id: params[:id])
  end

  def user_contacts
    current_user.contacts.order(name: :asc).page(params[:page]).per(params[:per_page])
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_contact.html.erb
<li id="<%= "#{dom_id(contact)}_container" %>" class="border-bottom">
  <%= turbo_frame_tag dom_id(contact) do %>
    <div class="row">
      <span class="col-1 text-wrap d-flex align-items-center">
        <%= contact.id %>
      </span>
      <span class="col-2 text-wrap d-flex align-items-center">
        <%= contact.name %>
      </span>
      <span class="col-1 text-wrap d-flex align-items-center">
        <%= contact.address %>
      </span>
      <span class="col-1 text-wrap d-flex align-items-center">
        <%= contact.birthdate %>
      </span>
      <span class="col-1 text-wrap d-flex align-items-center">
        <%= contact.last_4 %>
      </span>
      <span class="col-2 text-wrap d-flex align-items-center">
        <%= contact.email %>
      </span>
      <span class="col-2 text-wrap d-flex align-items-center">
        <%= contact.phone %>
      </span>
      <span class="col-1 d-flex align-items-center">
        <%= button_to contact_path(contact), class: 'btn btn-sm btn-danger', method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } } do %>
          Delete
        <% end %>
      </span>
    </div>
  <% end %>
</li>

app/views/contacts/_counter.html.erb
<div class="mb-2 row" id="contacts_counter">
  <div class="col text-center text-muted">
    <% if count > 0 %>
      Total contacts: <%= count %>
    <% else %>
      <i>No contacts are created yet</i>
    <% end %>
  </div>
</div>

app/views/contacts/create.html.erb
<h1>Contacts#create</h1>
<p>Find me in app/views/contacts/create.html.erb</p>

app/views/contacts/destroy.html.erb
<h1>Contacts#destroy</h1>
<p>Find me in app/views/contacts/destroy.html.erb</p>

app/views/contacts/destroy.turbo_stream.erb
<%= turbo_stream.remove "#{dom_id(@contact)}_container" %>
<%= turbo_stream.replace "contacts_counter" do %>
  <%= render partial: 'contacts/counter', locals: { count: @contacts.total_count } %>
<% end %>

app/views/contacts/edit.html.erb
<h1>Contacts#edit</h1>
<p>Find me in app/views/contacts/edit.html.erb</p>

app/views/contacts/index.html.erb
<h1>Contacts</h1>
<div class="d-flex justify-content-end">
  <%= link_to new_import_path, class: 'btn btn-primary' do %>
    <i class="fa-solid fa-upload"></i> Import contacts
  <% end %>
</div>
<div>
  <ul class="clean-list">
    <li class="border-bottom">
      <div class="headers row mt-4">
        <span class="col-1 fw-bold">
          ID
        </span>
        <span class="col-2 fw-bold">
          Name
        </span>
        <span class="col-1 fw-bold">
          Address
        </span>
        <span class="col-1 fw-bold">
          Birthdate
        </span>
        <span class="col-1 fw-bold">
          Last 4
        </span>
        <span class="col-2 fw-bold">
          Email
        </span>
        <span class="col-2 fw-bold">
          Phone
        </span>
        <span class="col-1 fw-bold">
          Actions
        </span>
      </div>
    </li>
    <%= render @contacts %>
  </ul>
</div>
<%= render partial: 'counter', locals: { count: @contacts.total_count } %>
<%= paginate @contacts %>

app/views/contacts/new.html.erb
<h1>Contacts#new</h1>
<p>Find me in app/views/contacts/new.html.erb</p>

app/views/contacts/show.html.erb
<h1>Contacts#show</h1>
<p>Find me in app/views/contacts/show.html.erb</p>

app/views/contacts/update.html.erb
<h1>Contacts#update</h1>
<p>Find me in app/views/contacts/update.html.erb</p>